export type ValidSkills =
  | "React"
  | "TypeScript"
  | "Next.js"
  | "Vercel"
  | "Tailwind CSS"
  | "Node.js"
  | "Laravel"
  | "Vue.js"
  | "PHP"
  | "C#"
  | "PostgreSQL"
  | "MySQL"
  | "Docker"
  | "GitLab"
  | "Unity"
  | "Dify"
  | "ChatGPT"
  | "Python"
  | "Presentation"
  | "Education"
  | "Communication"
  | "Microsoft365"
  | "Windows"
  | "Linux"
  | "Networking"
  | "DomainDNS"
  | "HTML"
  | "CSS"
  | "ProjectManagement"
  | "Workshop"
  | "AI"
  | "Research"
  | "Writing"
  | "TechnicalDocumentation";

export type ValidCategory =
  | "Full Stack"
  | "Frontend"
  | "Backend"
  | "UI/UX"
  | "Web Dev"
  | "Mobile Dev"
  | "3D Modeling";

export type ValidExpType = "Personal" | "Professional";

export type ValidPages =
  | "home"
  | "skills"
  | "ai"
  | "projects"
  | "experience"
  | "contact"
  | "resume";
