export const siteConfig = {
  name: "KOMORI TAKAFUMI | ポートフォリオ",
  authorName: "KOMORI TAKAFUMI",
  username: "your_id",
  description: "AI×自動化×フロントエンドで、個人と中小企業の成長を加速します。3日で動くPoC、30日で現場運用へ。",
  url: "https://your-domain.com",
  links: {
    twitter: "https://x.com/Null256x",
    github: "https://github.com/your_id",
    note: "https://note.com/null256",
    youtube: "https://www.youtube.com/@your_id",
    linkedin: "https://www.linkedin.com/in/%E8%B2%B4%E6%96%87-%E5%B0%8F%E6%A3%AE-53b079376/",
  },
  ogImage: "/images/ogp.jpg",
  iconIco: "/favicon.ico",
  logoIcon: "/logo.png",
  keywords: [
    "KOMORI TAKAFUMI",
    "AI",
    "自動化",
    "フロントエンド",
    "Next.js",
    "React",
    "TypeScript",
    "ポートフォリオ",
  ],
};
