export const siteConfig = {
  name: "KOMORI TAKAFUMI | ポートフォリオ",
  authorName: "KOMORI TAKAFUMI",
  username: "your_id",
  description: "AI×自動化×フロントエンドで、個人と中小企業の成長を加速します。3日で動くPoC、30日で現場運用へ。",
  url: "https://your-domain.com",
  links: {
    twitter: "https://x.com/your_id",
    github: "https://github.com/your_id",
    note: "https://note.com/your_id",
    youtube: "https://www.youtube.com/@your_id",
    linkedin: "https://www.linkedin.com/in/your_id",
  },
  ogImage: "/images/ogp.jpg",
  iconIco: "/favicon.ico",
  logoIcon: "/logo.png",
  keywords: [
    "KOMORI TAKAFUMI",
    "AI",
    "自動化",
    "フロントエンド",
    "Next.js",
    "React",
    "TypeScript",
    "ポートフォリオ",
  ],
};
